-- ============================================================================
-- Eklio — tenancy layer, lot 1: per-field brand source and logo import
-- ============================================================================
-- The provenance of a brand's fields — generated / imported / derived /
-- inherited — because the practice offer must reproduce an existing visual
-- identity exactly, and a clinician must inherit locked fields from the
-- practice charter. The map lives on site_specs, the same row as the fields
-- it describes (see the Step 0 inventory: site_specs is SPEC, not brand_kits).
-- ============================================================================


-- ============================================================================
-- 1. brand_kits.origin
-- ============================================================================

alter table public.brand_kits
  add column origin text not null default 'generated';

alter table public.brand_kits
  add constraint brand_kits_origin_check check (origin in ('generated', 'imported', 'mixed'));

comment on column public.brand_kits.origin is
  'Whether this kit''s brand was generated by Eklio, imported from an existing practice identity, or mixed (imported, then partly regenerated). Deliberately coarse — the field-by-field detail lives in site_specs.field_sources.';


-- ============================================================================
-- 2. site_specs.field_sources
-- ============================================================================
-- Allowed keys are derived from SPEC's actual editable columns: the six
-- colour roles and the typography pair map 1:1 to real site_specs columns.
-- `logo` is ONE conceptual key covering all four logo asset columns added
-- below — field_sources describes the provenance of a field the editor shows
-- the practitioner, not of an individual storage path.
--
-- ⚠ `tone` is NOT included. site_specs has no tone column — nothing on this
-- table is a "tone" field to source-track (project_briefs has a tone_card_id,
-- but that is brief input, not an editable SPEC field). Flagged in the
-- checkpoint report as a deviation from the literal brief, which named `tone`
-- among the allowed keys; omitted here because the instruction's own primary
-- rule is to derive the list from SPEC's actual columns, and there is no such
-- column.

alter table public.site_specs
  add column field_sources jsonb not null default '{}'::jsonb;

create or replace function public.validate_field_sources(p jsonb)
returns boolean
language sql
immutable
strict
set search_path = ''
as $$
  select coalesce(
    jsonb_typeof(p) = 'object'
    and not exists (
      select 1
        from jsonb_each_text(p) as kv(key, value)
       where kv.key not in (
               'primary_hex', 'secondary_hex', 'accent_hex',
               'light_neutral_hex', 'dark_neutral_hex', 'paper_hex',
               'heading_font', 'body_font', 'logo'
             )
          or kv.value not in ('generated', 'imported', 'derived', 'inherited')
    ),
  false)
$$;

comment on function public.validate_field_sources(jsonb) is
  'True iff every key of p is one of the nine tracked SPEC fields (six colour roles, heading_font, body_font, logo) and every value is one of generated/imported/derived/inherited. An empty object passes (no field has a recorded source yet). STRICT, so NULL input returns NULL — safe here only because site_specs.field_sources is NOT NULL, so the CHECK below never sees a NULL argument.';

-- Wired into a CHECK constraint, evaluated with the writing role's own
-- privileges (site_specs UPDATE is authenticated-only, RLS + column grants —
-- see 20260830060048_site_spec.sql). Unlike the repo's other 17 CHECK-wired
-- validators (deliberately left on Postgres's PUBLIC-EXECUTE default, per
-- 20260902090000_revoke_internal_function_surface.sql), this one is revoked
-- from anon explicitly: nothing about this function needs anon to reach it —
-- anon can never trigger this CHECK, since anon cannot write site_specs at
-- all — and closing it now is one fewer function for a future audit of the
-- other 17 to reconsider.
revoke execute on function public.validate_field_sources(jsonb) from public, anon;
grant  execute on function public.validate_field_sources(jsonb) to authenticated;

alter table public.site_specs
  add constraint site_specs_field_sources_check check (public.validate_field_sources(field_sources));

comment on column public.site_specs.field_sources is
  'Per-field provenance: key -> generated/imported/derived/inherited, for the six colour roles, heading_font, body_font, and logo. Read by the practice UI to show "why does this field look like this" and, later, to lock inherited fields. NOT enforced here — a client may still update a field marked inherited; rejecting that write is a later lot.';


-- ============================================================================
-- 3. Imported logo assets — Storage object paths
-- ============================================================================

alter table public.site_specs
  add column logo_svg_path        text,
  add column logo_png_light_path  text,
  add column logo_png_dark_path   text,
  add column monogram_svg_path    text;

alter table public.site_specs
  add constraint site_specs_logo_svg_path_check
    check (logo_svg_path is null or logo_svg_path like 'org/%'),
  add constraint site_specs_logo_png_light_path_check
    check (logo_png_light_path is null or logo_png_light_path like 'org/%'),
  add constraint site_specs_logo_png_dark_path_check
    check (logo_png_dark_path is null or logo_png_dark_path like 'org/%'),
  add constraint site_specs_monogram_svg_path_check
    check (monogram_svg_path is null or monogram_svg_path like 'org/%');

comment on column public.site_specs.logo_svg_path is
  'Storage object path in the brand-logos bucket, org/<organization_id>/... . Null until a logo is imported. Never validated as a real vector file here — that is an application concern.';


-- ============================================================================
-- 4. font_display_fallback
-- ============================================================================

alter table public.site_specs
  add column font_display_fallback text;

comment on column public.site_specs.font_display_fallback is
  'The declared font (heading_font/body_font) is the one the practice owns; the fallback is a freely-licensed font used only for on-screen preview and PDF rendering when the declared font cannot be served. Font files are never uploaded.';


-- ============================================================================
-- 5. Storage bucket brand-logos
-- ============================================================================
-- Private bucket, path shape org/<organization_id>/<file>. Any active member
-- (owner or clinician) may read/write — lock enforcement on who may replace
-- the practice charter's logo is a later lot, same as field_sources above.

insert into storage.buckets (id, name, public)
values ('brand-logos', 'brand-logos', false)
on conflict (id) do nothing;

-- storage.foldername(name)[2] is attacker-controlled text (the object path a
-- client uploads to), so casting it to uuid can raise. A cast failure inside
-- an RLS predicate must read as "no access", not as a 500 — this wraps the
-- cast so an exception becomes false, never an error.
create or replace function public.can_access_org_logo_path(p_name text)
returns boolean
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_folders text[];
  v_org_id  uuid;
begin
  v_folders := storage.foldername(p_name);

  if v_folders is null or array_length(v_folders, 1) < 2 or v_folders[1] <> 'org' then
    return false;
  end if;

  begin
    v_org_id := v_folders[2]::uuid;
  exception when others then
    return false;
  end;

  return public.is_org_member(v_org_id);
end;
$$;

comment on function public.can_access_org_logo_path(text) is
  'True iff p_name (a storage.objects.name) is shaped org/<uuid>/... and the calling user is an active member of that organization. A malformed second path segment (not a uuid) is caught and returns false rather than raising.';

revoke execute on function public.can_access_org_logo_path(text) from public, anon, authenticated;
grant  execute on function public.can_access_org_logo_path(text) to authenticated;

create policy "brand_logos_select_org"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'brand-logos' and public.can_access_org_logo_path(name));

create policy "brand_logos_insert_org"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'brand-logos' and public.can_access_org_logo_path(name));

create policy "brand_logos_update_org"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'brand-logos' and public.can_access_org_logo_path(name))
  with check (bucket_id = 'brand-logos' and public.can_access_org_logo_path(name));

create policy "brand_logos_delete_org"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'brand-logos' and public.can_access_org_logo_path(name));
